//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceDanceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.Competition_Couple = new HashSet<Competition_Couple>();
        }
    
        public int CompetitionID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CountryFK { get; set; }
        public Nullable<int> JudgeFK1 { get; set; }
        public Nullable<int> JudgeFK2 { get; set; }
        public Nullable<int> JudgeFK3 { get; set; }
        public Nullable<int> JudgeFK4 { get; set; }
        public Nullable<int> JudgeFK5 { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Judge Judge { get; set; }
        public virtual Judge Judge1 { get; set; }
        public virtual Judge Judge2 { get; set; }
        public virtual Judge Judge3 { get; set; }
        public virtual Judge Judge4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_Couple> Competition_Couple { get; set; }
    }
}
