//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceDanceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Couple()
        {
            this.Competition_Couple = new HashSet<Competition_Couple>();
        }
    
        public int CoupleSK { get; set; }
        public Nullable<int> FemaleCompetitorFK { get; set; }
        public Nullable<int> MaleCompetitorFK { get; set; }
        public Nullable<int> CoachFK { get; set; }
        public Nullable<int> CountryFK { get; set; }
    
        public virtual Coach Coach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_Couple> Competition_Couple { get; set; }
        public virtual Competitor Competitor { get; set; }
        public virtual Competitor Competitor1 { get; set; }
        public virtual Country Country { get; set; }
    }
}
