//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceDanceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<Competition_Couple> Competition_Couple { get; set; }
        public virtual DbSet<Competitor> Competitor { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Couple> Couple { get; set; }
        public virtual DbSet<Judge> Judge { get; set; }
    }
}
